#!/bin/bash
set -e

echo "Configuring PHP-FPM Proxy"
if [[ $PHP_FPM_HOST != "" ]]; then
    PHP_FPM_HOST="php-fpm"
fi
sed -i 's/php-host/'$PHP_FPM_HOST'/g' /etc/nginx/conf.d/default.conf

if [[ $PHP_FPM_PORT != "" ]]; then
    PHP_FPM_PORT=9000
fi
sed -i 's/php-port/'$PHP_FPM_PORT'/g' /etc/nginx/conf.d/default.conf

echo "Expecting PHP-FPM service at $PHP_FPM_HOST:$PHP_FPM_PORT"

exec nginx
