FROM greencape/base:latest
MAINTAINER Niels Braczek <nbraczek@bsds.de>

ENV MARIADB_MAJOR %%MARIADB_MAJOR%%
ENV MARIADB_VERSION %%MARIADB_VERSION%%

ADD . /build.d

RUN /build.d/install.sh

VOLUME /var/lib/mysql

EXPOSE 3306

CMD ["/sbin/my_init"]
